const CHAT_TYPES = {
  FETCH_HISTORY_LOADING: 'FETCH_HISTORY_LOADING',
  FETCH_HISTORY_SUCCESS: 'FETCH_HISTORY_SUCCESS',
  FETCH_HISTORY_FAILURE: 'FETCH_HISTORY_FAILURE',
  SEND_MESSAGE_LOADING: 'SEND_MESSAGE_LOADING',
  SEND_MESSAGE_USER: 'SEND_MESSAGE_USER',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
  SET_TYPING: 'SET_TYPING',
} as const;

export default CHAT_TYPES;
